### ISSUE TITLE
agent memory status info misleading

### ISSUE THREAD

**Issue by robcza** [whalebone/local-resolver-agent#12]
I have encountered an issue with the hardware status in sysinfo. This is the memory status reported by the agent:
```
    "memory": {
      "total": 3,
      "free": 1,
      "usage": 45
    },
```

This is the info reported by the system directly:
```
[root@tst-dns-work ~]# free -h
              total        used        free      shared  buff/cache   available
Mem:           3.7G        1.2G        1.8G        207M        680M        2.0G
Swap:            0B          0B          0B
```

Is it possible to report the memory with floating point? There is a huge difference between `3` and `3.7` and we need to check this in order to report to the customer a violation of our minimal requirements.

**Comment by Narzhan** [comment]
It is possible however the decimal part will be rounded 3.85 -> 3.9.

**Comment by Narzhan** [comment]
Can be found in 1.3, all usage info (disk and ram) are now floating.

**Comment by robcza** [comment]
Will be part of the next release
