### ISSUE TITLE
add image tags to sysinfo

### ISSUE THREAD

**Issue by robcza** [whalebone/local-resolver-agent#13]
We should add image tags of the running containers in the sysinfo message structured like this:
```json
{
  "images" : { 
    "kresman": "whalebone/kresman:1.2",
    "resolver": "whalebone/kres:2.3.1"
  }
}
```
The reason is, we need to verify several things:
- what customers have what versions installed
- whether the update actually went through and they are running the proper images

**Comment by Narzhan** [comment]
Can be found in 1.3.

**Comment by robcza** [comment]
Will be part of the next release
