### ISSUE TITLE
Implement mem_limit docker-compose support

### ISSUE THREAD

**Issue by robcza** [whalebone/local-resolver-agent#15]
We will need the support for limiting memory in the docker compose for individual containers/services.

Format could be either the old one:
`mem_limit: 1536m`

Or the newer one:
```
      resources:
        limits:
          memory: 1536m
```

**Comment by Narzhan** [comment]
It would be easier to use the old format from the sdk point of view. I propose to do it that way for convenience and use the docker-compose as a template for agent since cpu-shares are also present incorrectly.

**Comment by robcza** [comment]
@narzhan that seems ok, as we use it for internal purposes only
Could it introduce issues if we want to validate the compose on server side?

**Comment by Narzhan** [comment]
I guess that would depend on the type of validation we would like to have. If we were to use docker-compose native config check than it would return an error (same as cpu_shares, both of these would have to be rewritten to ver. 3 syntax). But the python docker sdk uses names from docker-compose <2, in most cases, this is used to evaluate names (keys) for the container creation so it is more convenient to do it this (hybrid) way. Again that would depend on the validation on, portal from the context, side. Agent accepts only a subset of keys from docker-compose so validation on agent's side is trivial, or I should say: incorrect values are omitted.

**Comment by robcza** [comment]
Ok, lets stick to sdk v2
